dita-ot/docs

- user-guide/pdf2-creating-change-bars.dita
- user-guide/publishing.ditamap
Here's my initial stab at documenting the change bar creation details for PDF2.
> Initial draft of PDF2 change bar creation topic

- dev_ref/plugin-overridestyle.dita
Changed to gerund style to match other plug-in topics.
> Made title of plug-in topic consistent

- dev_ref/XhtmlCommon.dita
- dev_ref/preprocess-chunk.dita
- dev_ref/preprocess-coderef.dita
- dev_ref/preprocess-conref.dita
- dev_ref/preprocess-debugfilter.dita
- dev_ref/preprocess-flagging.dita
- dev_ref/preprocess-keyref.dita
- dev_ref/preprocess-maplink.dita
- dev_ref/preprocess-mapref.dita
- dev_ref/preprocess-metadata.dita
- dev_ref/preprocess-topicpull.dita
- dev_ref/processing-order.dita
- user-guide/DITA-globalization.dita
- user-guide/DITA_v1-3-support.dita
- user-guide/building-with-ant.dita
- user-guide/dita2troff.dita
- user-guide/enabling-debug-mode.dita
- user-guide/globalization-supported-in-dita-ot.dita
- user-guide/pdf2-creating-change-bars.dita
- user-guide/reducing-processing-time.dita
Implement xml-d for User's Guide and Developer's Reference. Does not include topics that are programmatically generated and source for conref push.
> Implement XML mention domain

- user-guide/pdf2-creating-change-bars.dita
Corrected style and markup for this topic. (It still needs to be relocated elsewhere in the navigation.)
> Edit change bar topic to conform to style guidelines

- dev_ref/preprocess-flagging.dita
Replace dl element with parml element.
> Correct markup in preprocess-flagging.dita topic

- dev_ref/plug-ins.ditamap
- dev_ref/plugin-configfile.dita
- dev_ref/using-plugin-URI-extension.dita
@keberlein , @infotexture ,
Here are a couple incremental commits for the Creating plug-ins section. I'm still working on the new/revised topics for creating new extension points, but the two commits here I believe provide some key information about creating plug-ins that's been missing to date.
I'm looking forward to your suggestions, revisions, or later improvements to this information.
> plugin-configfile and abstracting plug-in path references

- user-guide/DITA-messages-details.xml
Tweaks to two existing "additional info" sections for PDF, along with new "additional info" for some other PDF messages.
> Message updates to go with #1709

- release-notes/index.dita
I know these need editing, particularly to match the style of release notes for the last several versions. But I think some of these should be good enough, and for most items it should be possible to flesh out the language without having to refer back to individual issues.
I left the SASS ones for @infotexture because he'll know them better anyway.
> First draft of issue descriptions

- dev_ref/dev_ref.ditamap
- dev_ref/preprocess-branch-filter.dita
- dev_ref/preprocess-clean-map.dita
- dev_ref/preprocess-copy-to.dita
- dev_ref/preprocess-copyfiles.dita
- dev_ref/preprocess-flagging.dita
- dev_ref/preprocess-profile.dita
- dev_ref/preprocess-topic-fragment.dita
* `branch-filter`
* `copy-to`
* `profile`
* `topic-fragment` (renamed `coderef`)
* `clean-map`
Signed-off-by: Roger Sheen <roger@infotexture.net>
> Add topic stubs for missing pre-processing steps

- user-guide/log-files.dita
Signed-off-by: Stefan Eike <stefan.eike@mailbox.org>
> Explain how to set a custom logger

- topics/plugin-messages.dita
Signed-off-by: Stefan Eike <stefan.eike@mailbox.org>
PR for #186
> Update root element in messages example

- release-notes/index.dita
In "Resolved Issues" > "Features" section.
Signed-off-by: François Violette <francoisviolette@gmail.com>
> Fix typo (missing "to")

- release-notes/index.dita
Draft release notes for 2908, 2909, 2912.
> Add release notes for last two issues

- release-notes/index.dita
> Draft 3.1.2 release notes

- resources/reltable.ditamap
- resources/source-files.ditamap
- samples/plugins/com.example.html5-javascript/build_html5-javascript.xml
- samples/plugins/com.example.html5-javascript/include/javascript.ftr.xml
- samples/plugins/com.example.html5-javascript/plugin.xml
- topics/html-customization-plugin-javascript.dita
- topics/html-customization-plugins.dita
- topics/html-customization.ditamap
This PR adds a new custom plug-in example that demonstrates how to embed JavaScript in HTML5 output.
> Add JavaScript plug-in example

- topics/alternative-input-formats.dita
I did a real simple one to make sure I'm doing the PR correctly.
> Add a mention of XDITA in addition to MDITA and HDITA

- topics/lwdita-input.dita
Signed-off-by: markgif <m1879@earthlink.net>
> Add XDITA section and more about MDITA and HDITA

- release-notes/index.dita
> Draft release notes for several 3.3 items

- topics/plugin-javalib.dita
Added details about the classpath configuration 
Signed-off-by: Eliot Kimber <ekimber@contrext.com>
> Added details to topic on java lib extension point

- resources/source-files.ditamap
- topics/implement-saxon-collation-uri-resolvers.dita
- topics/implement-saxon-customizations.dita
- topics/implement-saxon-extension-functions.dita
- topics/plug-ins.ditamap
Supporting documentation for the saxon customization fixes and enhancements I submitted to the dita-ot project.
Signed-off-by: Eliot Kimber <ekimber@contrext.com>
> Document saxon customization features.

- topics/plugin-configfile.dita
> Added @deprecated and @required info to <param>.

- release-notes/index.dita
Adding draft info about each item in 3.3.4.
Also added (commented-out) draft info about 3356, which was created earlier today but still needs review / merging.
> Draft notes for 3.3.4

- README.md
---
name: Pull request
about: Propose changes to fix an issue or implement a new feature
---
- Bug fix _(non-breaking change which fixes an issue)_
- Breaking change _(fix or feature that changes existing functionality)_
> Fix link to contribution guidelines

- resources/external-links.ditamap
- resources/source-files.ditamap
- topics/project-files-json.dita
- topics/project-files-xml.dita
- topics/project-files-yaml.dita
- topics/publishing.ditamap
- topics/using-project-files.dita
> Initial documentation for project files

- parameters/ant-parameters-details.dita
- parameters/dita-command-arguments.dita
- parameters/generate-copy-outer.dita
- reference/implementation-dependent-features.dita
- release-notes/index.dita
- resources/reusable-components.dita
- topics/log-files.dita
- topics/markdown-dita-syntax-reference.dita
- topics/migrating-to-1.8.dita
- topics/migrating-to-2.1.dita
- topics/migrating-to-2.3.dita
- topics/migrating-to-2.4.dita
- topics/migrating-to-2.5.dita
- topics/migrating-to-3.0.dita
- topics/migrating-to-3.3.dita
- topics/pdf-customization-approaches.dita
- topics/plugin-coding-conventions.dita
- topics/plugin-configfile.dita
- topics/plugins-registry.dita
- topics/prerequisite-software.dita
Signed-off-by: Lief Erickson <lief.erickson@scriptorium.com>
> Remove <div> surrounding indexterms

- resources/external-links.ditamap
- resources/source-files.ditamap
- resources/subjectscheme-outputclass.ditamap
- topics/publishing.ditamap
- topics/using-docker-images.dita
Per https://github.com/dita-ot/dita-ot/pull/3358
> Initial documentation for Docker images

- release-notes/index.dita
Slight revision to release notes description of indexing fixes.
> Revise description of index fixes

- release-notes/index.dita
Signed-off-by: Robert D Anderson <gorodki@gmail.com>
---
name: Pull request
about: Propose changes to fix an issue or implement a new feature
---
Adds draft content to release notes for several new DITA-OT 3.5 issues.
> Add draft notes for 3.5 issues, primarily DITA 2.0 related

- .github/workflows/preview.yml
Add GitHub Actions to deploy a PR preview.
> Add PR preview

- README.md
> Add step to check git is on $PATH

- README.md
> Add Git as prereq for Husky

- parameters/ant-parameters-details.dita
- resources/params.xsl
Include params from transtypes that extend the transtype being processed.
> Include params from transtypes that extend the transtype

- resources/key-definitions.ditamap
> Update Saxon version

- reference/dita-v2-0-support.dita
- release-notes/index.dita
Update description for #3780 - Support fileset for style configuration description
> Add DITA 2.0 changes

- release-notes/index.dita
- resources/reltable.ditamap
- resources/reusable-components.dita
- resources/source-files.ditamap
- samples/plugins/com.example.print-pdf/cfg/common/vars/en.xml
- topics/add-new-gentext-language.dita
- topics/adding-new-strings.dita
- topics/globalizing.ditamap
- topics/migrating-to-3.7.dita
- topics/overriding-a-default-generated-text-string.dita
- topics/plugin-addgeneratedtext.dita
Describe the new `variables` structure for generated text from https://github.com/dita-ot/dita-ot/pull/3817
> New generated text variables structure

- topics/adding-new-strings.dita
The example shows how to use the same strings in various languages.
Added an example showing how to add strings to multiple languages.
Tested on my local machine.
Docs improvement
> Adding an example

- parameters/ant-parameters-details.dita
- parameters/dita-command-arguments.dita
- release-notes/index.dita
- resources/conref-task.dita
- resources/key-definitions.ditamap
- samples/docker/Dockerfile
- topics/prerequisite-software.dita
- It will not be merged via the GitHub UI. 
> 🚧 Draft 3.7.1 docs

- release-notes/index.dita
- resources/key-definitions.ditamap
- samples/docker/Dockerfile
- It will not be merged via the GitHub UI. 
> 🚧 Draft 3.7.2 docs

- release-notes/index.dita
- resources/external-links.ditamap
- resources/key-definitions.ditamap
- samples/docker/Dockerfile
- topics/reducing-processing-time.dita
- It will not be merged via the GitHub UI. 
> 🚧 Draft 3.7.3 docs

- release-notes/index.dita
- resources/key-definitions.ditamap
- samples/docker/Dockerfile
> 🚧 Draft 3.7.4 docs

- .github/actions/render/action.yml
- .github/workflows/release.yml
Update CI workflows to use DITA-OT 4.0.
Keep up with latest DITA-OT release and support latest Markdown features.
> Update CI to DITA-OT 4.0

- resources/dita-ot-day-video-keys.ditamap
- resources/ditaotdaykeys/dita-ot-day-2022-keys.ditamap
- resources/source-files.ditamap
- topics/dita-ot-day-2022.ditamap
- topics/dita-ot-day-videos-intro-2022.dita
- topics/dita-ot-day-videos.ditamap
Fixes https://github.com/dita-ot/docs/issues/446.
Built locally with Gradle
> Add DITA-OT Day 2022 videos

- resources/conref-task.dita
- resources/source-files.ditamap
- topics/plug-ins.ditamap
- topics/plugin-preprocess-xslt.dita
Add plug-in example to transform topics with XSLT after preprocess.
[Preview](https://preview-pr-486--dita-ot.netlify.app/dev/topics/plugin-preprocess-xslt.html)
Current plug-in examples don't cover this use case.
> Add plug-in example to transform topics with XSLT after preprocess

- .github/actions/render/action.yml
- .github/workflows/release.yml
Update docs GitHub Actions for 4.1.2.
> Update docs GitHub Actions for 4.1.2

- .github/workflows/release.yml
Add support for calling workflow from core repo workflow.
> Add support for calling workflow from core repo workflow

- README.md
> [#509] Revise instructions for building from dita-ot repo

- release-notes/index.dita
> Draft 4.2.1 Release Notes

- .github/actions/render/action.yml
- .github/workflows/release.yml
Update docs GitHub Actions for 4.2.1.
> Update docs GitHub Actions for 4.2.1

- .github/actions/render/action.yml
- .github/workflows/release.yml
Update docs GitHub Actions for 4.2.2.
> Update docs GitHub Actions for 4.2.2

- .github/actions/render/action.yml
- .github/workflows/release.yml
Update docs GitHub Actions for 4.2.3.
> Update docs GitHub Actions for 4.2.3

- .github/actions/render/action.yml
- .github/workflows/release.yml
Update docs GitHub Actions for 4.2.4.
> Update docs GitHub Actions for 4.2.4

- parameters/dita-command-arguments.dita
Add documentation for `init` subcommand.
Documents addition of dita-ot/dita-ot#4509
> Add init subcommand

- parameters/dita-command-arguments.dita
Validate subcommand documentation.
dita-ot/dita-ot#4397
- What documentation changes are needed for this feature?
_(Provide links to existing documentation topics that will require updates)_
- Will this change affect backwards compatibility or other users' overrides?
> Add validate subcommand

- samples/themes/dita-ot-docs-theme.yaml
Update docs PDF theme file to build on `default` theme implementation in https://github.com/jelovirt/pdf-generator/pull/114.
> Update bookmap theme

- .github/actions/render/action.yml
- .github/workflows/release.yml
Update docs GitHub Actions for 4.3.
> Update docs GitHub Actions for 4.3

- parameters/ant-parameters-details.dita
- release-notes/index.dita
- resources/key-definitions.ditamap
- samples/docker/Dockerfile
> 🚧 Draft 4.3.1 docs

- .github/actions/render/action.yml
- .github/workflows/release.yml
Update docs GitHub Actions for 4.3.1.
> Update docs GitHub Actions for 4.3.1

- reference/reference.ditamap
- release-notes/index.dita
- resources/external-links.ditamap
- resources/key-definitions.ditamap
- resources/reltable.ditamap
- samples/docker/Dockerfile
- topics/error-messages-details.xml
- topics/plugin-messages.dita
> 🚧 Draft 4.3.3 docs

- .github/actions/render/action.yml
- .github/workflows/release.yml
Update docs GitHub Actions for 4.3.3.
> Update docs GitHub Actions for 4.3.3

- release-notes/index.dita
- resources/key-definitions.ditamap
- samples/docker/Dockerfile
> 🚧 Draft 4.3.4 docs
