site.gradle
This will cause Gradle to rerun the related tasks when the XSLT files
are changed.
=> Declare XSLT files as input files

build.xml, resources/properties-file.xsl
Related to https://github.com/dita-ot/docs/pull/58, generate an annotated template.properties file with comments describing the various build parameters (generated from the same code as the documentation).
=> Generate annotated samples/template.properties file

dev_ref/migrating-to-1.5.4.dita, dev_ref/migrating-to-1.6.dita, dev_ref/migrating-to-1.7.dita, dev_ref/migrating-to-1.8.dita, dev_ref/plugin-xmlcatalog.dita, user-guide/pdf2-creating-change-bars.dita
Per The IBM Style Guide, topic titles should use sentence-style
capitalization. Most of the DITA-OT docs currently aligns with the style
guidelines.
=> Use sentence-style capitalization in titles

user-guide/DITA_v1-3-support.dita
Remove commented code that is not relevant now, as the DITA 1.3 is a released specification.
=> Remove a comment containing code that is not relevant anymore

user-guide/DITA-globalization.dita
I don't think the toolkit actually uses `@translate` in default processing -- it's definitely a useful DITA attribute for globalization, but I can't think of how our default processing would use it or change based on its value.
=> Remove mention of @translate

user-guide/globalization-supported-in-dita-ot.dita
Updated to add cross reference to configuration.properties, which can be used to change the default language.
Also noticed and addressed a couple of draft comments from Kris.
=> Add cross reference to configuration option

dev_ref/html-customization-plugin-bundle-css.dita
Added precisions to context for newbies (as a former noob)
I added a few precisions to the list in the context section. I know I had problems understanding this part when I first started tinkering with plugins. 
I may be a bit too detailed...
=> Clarify CSS parameters in <context>

site.gradle
0.2.1 fixes the rather confusing (to the user of the plugin) issue https://github.com/eerohele/saxon-gradle/issues/5.
In `site.gradle`, the issue manifested in having to call `project.toURI` instead of just `toURI`, so I've modified those instances as well.
I also refactored the `toURI` function to work correctly on Windows.
=> Update saxon-gradle plugin version to 0.2.1

dev_ref/plugin-newtranstype.dita
The docs currently use HTML5 as an example that extends another transform, but as of 2.4 this is no longer true. I've tweaked the language to point out that this remains a good example, but technically applies to earlier versions of that plugin.
Potential longer term alternatives: create a full example, use XHTML (which is much longer and sort of out of date), or HTML Help (which is really short but REALLY out of date), or just use an abbreviated version of another plugin.
=> Tweaking technically innacurate (obsolete) info

dev_ref/plugin-newextensions.dita
=> Fixed typo in doc. There was no closing target tag.

user-guide/DITA-messages-details.xml
These updates go with changes in https://github.com/dita-ot/dita-ot/pull/2637 and https://github.com/dita-ot/dita-ot/pull/2569 for DITA-OT 2.5.
=> Add details for DOTJ070I, DOTJ071E, tweak DOTJ030I

parameters/internal-ant-properties.dita
Draft description to go with new parameter created with https://github.com/dita-ot/dita-ot/pull/2670
It would probably be best to hold off on merging until the main pull request is accepted...
=> Describe internal property temp.output.dir.name

user-guide/reducing-processing-time.dita
[DITA-OT 2.4 and newer require Java 8.](http://www.dita-ot.org/2.4/release-notes/index.html#ID__requirements) Noting that DITA-OT 2.0 requires Java 7 without including this context can lead to confusion if this is the first page of documentation a user encounters.
=> Note in performance section that OT 2.4 requires Java 8

parameters/dita-command-arguments.dita, resources/conref-task.dita
It would be easier for starters, if the docs would name the corresponding parameters for the dita command arguments.
=> Map common parameters to arguments

build.xml, samples/properties/docs-build-html5.properties
This PR refactors the distribution docs build to use the `dita` command to pick up the classpath settings and new library dependencies required by external plug-ins.
It is not intended to be merged yet 'as is', but rather to serve as a basis for discussion on the best way to refactor the build to meet the new requirements.
One open issue with this approach is that the `.properties` files used in earlier releases used `${basedir}` to anchor the absolute paths required for parameters such as `args.hdr`, as in [docs-build-html5.properties](https://github.com/dita-ot/docs/blob/develop/samples/properties/docs-build-html5.properties#L17).
@jelovirt The `${basedir}` approach worked with Ant, but throws errors when building with the `dita` command. How can we define portable paths for parameters …
=> Refactor build to use `dita` command

resources/external-links.ditamap, user-guide/DITA_v1-2-support.dita, user-guide/DITA_v1-3-support.dita
The content in these topics is quite outdated, and gives no-longer-useful information such as what version of DITA-OT 1.x added specific features of DITA 1.2.
This pull request cleans up the two topics, adds a bit of new information, updates links from the base spec to errata 01, and moves all of the links to keys.
The TOC currently has DITA 1.2 before DITA 1.3, which feels like it's "in order" but I'd suggest flipping that order because 1.3 support is far more important / relevant than 1.2 support at this point. Haven't put that in this pull request though because I know those maps are heavily in flux.
Another long-term cleanup item -- I noticed some of the existing keys for the spec use names like `dita-ot-spec` but should really be `dita-spec` or `dita13-spec` (because it's the DITA …
=> Clean up topics on DITA 1.2 and DITA 1.3

dev_ref/map-first-preprocessing.dita
Rewrite of the topic on map-first processing introduced in 2.5, to provide more detail, information about how to test in your own custom transformation types, as well as known limitations.
=> Draft info about mapfirst process, how to test

dev_ref/html-customization-plugin-bundle-css.dita
Changed "value" to "file" so the plugin integrates and prevents 'does not exist in the project "DOST"' error message.
=> Fix syntax error in sample plugin.xml file

topics/DITA-messages-details.xml
Had a customer run into a DOTJ054E message that looked roughly like this:
```
inputfile.dita:39:95: [DOTJ054E][ERROR] Unable to parse invalid href attribute value "mailto:Sample Example/Austin/IBM", using 'mailto:Sample%20Example/Austin/IBM'.
```
Seeing this in a terminal with other log info, he didn't catch the change to `%20` and was confused why a seemingly valid link marked with `scope="external"` generated a message. 
The correct fix of course is to change the source, but I noticed our doc doesn't really give any detail for this message, and I've nearly always seen it come up with unescaped space characters, so thought perhaps the doc should suggest that. (This isn't the first time I've had somebody complain about the message for exactly this reason.)
=> Suggested detail for DOTJ054E

samples/hierarchy.ditamap, samples/sequence.ditamap, samples/tasks/washingthecar.xml
I know these samples are not exactly stellar, and of limited utility. That said, last week I was looking ahead to DITA 2.0 where these deprecated attributes will be removed. So when I saw them a few minutes ago in our samples, it seemed we should go ahead and update them.
=> Convert deprecated attributes to elements

release-notes/index.dita, topics/migrating-to-3.1.dita
Minor edits to use or reject for the 3.1 release info.
Changes add `<xmlelement>` around one instance of "codeblock" and provide more specifics about the changes to use `if:set` and `unless:set`.
=> Minor edits to release info

resources/extension-points.xsl
Noticed that we have a problem in the docs today, now that we generate a summary topic with [ALL DITA-OT extension points](https://www.dita-ot.org/dev/extension-points/all-extension-points.html):
- We generate a topic for each plug-in with extension points. This defines the extension point `dita.conductor.target`.
- That target is obsolete; it's in our manually authored topic about [general extension points](https://www.dita-ot.org/dev/extension-points/plugin-extension-points-general.html), but with a note saying it's obsolete / deprecated. This note is pushed into the generated topic.
- We now *also* generate a summary topic with [ALL DITA-OT extension points](https://www.dita-ot.org/dev/extension-points/all-extension-points.html). …
=> Fix / enhance topic for all extension points

.gitattributes, build.gradle, resources/properties-file.xsl
When the docs Ant build was replaced with the new Gradle build for #178, the `generate-properties-file` target created by @shaneataylor for 2.3 with #60 was inadvertently left behind.
After the distribution build for the core repo was updated to use the docs Gradle build for version 3.1 per dita-ot/dita-ot#2972, the `template.properties` file was no longer generated when the docs build ran.
This PR ports the missing target from the old Ant build to the current Gradle build file to ensure that the template is once again available in the `docsrc/samples/properties/` directory of distribution builds, and updates the template stylesheet to use the GNU double-hyphen syntax introduced in 2.4 for CLI options.
=> Restore autogenerated properties template

release-notes/index.dita
The bug list in there contains 3.0 bugs, it looks like the wrong link was used to correct them. I left those alone with this update.
Added descriptions to items I worked on for 3.2 -- also merged some that were listed in both feature / enhancement section (one with issue one with pull request).
=> Draft feature/enhancement items for 3.2 notes

topics/plugins-registry.dita
Much editing probably required -- but added instructions based on how I tested / added the morse plugin, with config entry
`registry = http://plugins.dita-ot.org/ https://raw.githubusercontent.com/robander/registry/feature/morse/`
=> Instructions to test your registry entry

samples/ant_sample/dita-cmd.xml, topics/migrating-ant-to-dita.dita
This PR updates the existing `<dita-cmd>` macro to do the following:
* Work on both Windows and Linux machines
* Fail on error to avoid `build failed/build successful errors` - see https://groups.google.com/forum/#!topic/dita-ot-users/eVpktG7oluQ as an example
* Use `--` format for parameters
* User `arg value` parameters - related #250
* Added `taskname="dita-cmd"` to ensure that you can see that `dita-cmd` is failing when an error occurs.
Signed-off-by: Jason Fox <jason.fox@fiware.org>
=> Amend exec command to fail on error

resources/subjectscheme-outputclass.ditamap, resources/subjectscheme.ditamap
Add subjectScheme values for `@outputclass`.
Discussion with @infotexture and @keberlein led me to create an inventory of the `@outputclass` values used throughout the docs. The goal is to limit and control what `@outputclass` values are used on certain elements. The `@outputclass` values can be used for styling or to add semantics (e.g., `<codeph>`) without specialization.
=> Add @outputclass controlled values

reference/extended-functionality.dita, reference/flagging-migration.dita, reference/preprocess-flagging.dita, reference/preprocess-mapref.dita, reference/processing-order.dita, topics/implement-saxon-collation-uri-resolvers.dita, topics/implement-saxon-customizations.dita, topics/implement-saxon-extension-functions.dita, topics/migrating-to-1.5.4.dita, topics/migrating-to-3.3.dita, topics/pdf-plugin-structure.dita, topics/pdf2-creating-change-bars.dita, topics/plugin-best-practices.dita, topics/plugin-coding-conventions.dita, topics/using-plugin-URI-extension.dita
Add `@outputclass="language-xml"` to `<codeblock>` where appropriate.
dita-ot/website#216 adds new styling capabilities for site output. Some of this styling is dependent on `@outputclass`. This PR adds the `@outputclass` or the `language-xml` to additional source files.
Built website locally with gradle using dita-ot/website@fbbd745d. Build successfully showed XML elements and attributes with styling. 
Built website locally with gradle using dita-ot/website@91db9e3c. Build completed successfully, but no styling was present. This is expected.
Built PDF locally and styling was as expected (i.e., no colors).
=> Add 'language-xml' to @outputclass

index.dita, resources/common-toc.ditamap, topics/alternative-input-formats.dita, topics/publishing.ditamap, topics/transformations.ditamap, userguide-book.ditamap
The [output formats](https://www.dita-ot.org/dev/topics/output-formats.html) section has been buried under [Building output](https://www.dita-ot.org/dev/topics/building-output.html), but as a transformation tool, it seems like this deserves a more prominent location in the table of contents.
=> Promote “output formats” to top level of ToC

parameters/ant-parameters-details.dita, reference/preprocess-copyfiles.dita, reference/preprocessing.dita, topics/DITA-messages-details.xml, topics/alternative-input-formats.dita, topics/custom-plugins.dita, topics/html-customization-plugin-javascript.dita, topics/html-customization.dita, topics/implement-saxon-collation-uri-resolvers.dita, topics/implement-saxon-customizations.dita, topics/markdown-dita-syntax-reference.dita, topics/migrating-to-1.5.4.dita, topics/migration.dita, topics/pdf-customization.dita, topics/pdf-plugin-structure.dita, topics/pdf-plugin-structure_fo-xsl.dita, topics/pdf2-creating-change-bars.dita, topics/plugin-applications.dita, topics/plugin-coding-conventions.dita
Due to a misunderstanding of how index ranges are designed the markup has been removed by deleting the `@end` entry and retaining the content of `@start`. [#3318 ](https://github.com/dita-ot/dita-ot/issues/3318) 
Signed-off-by: Lief Erickson <lief.erickson@scriptorium.com>
=> Remove index range markup

topics/using-docker-images.dita
---
name: Pull request
about: Docker image instructions
---
This adds the `repo` scope to the instructions around creating a GitHub access token. The token needs both `repo` and `read:packages` scopes, or you'll get the following error when you try to do anything with the container (pull, build etc.): 
"Your token has not been granted the required scopes to execute this query. The 'name' field requires one of the following scopes: ['repo'], but your token has only been granted the: ['read:packages'] scopes."
=> Missing 'repo' scope for access token

build.gradle, resources/site.ditaval
In dita-ot.org build, output `@platform` attribute into HTML5 `data-platform` attribute.
When platform information is retained in HTML5 output, the data can be used for dynamic filtering.
=> Output platform profile attributes in website build

parameters/dita-command-arguments.dita, resources/subjectscheme-outputclass.ditamap, topics/building-with-ant.dita, topics/creating-docker-images.dita, topics/determining-version-of-ditaot.dita, topics/dita-command-help.dita, topics/html-customization-properties-file.dita, topics/increasing-the-jvm.dita, topics/installing-via-homebrew.dita, topics/logging.dita, topics/migrating-to-3.4.dita, topics/plugins-installing.dita, topics/plugins-registry.dita, topics/plugins-removing.dita, topics/project-files-json.dita, topics/using-dita-command.dita, topics/using-dita-properties-file.dita, topics/using-docker-images.dita, topics/using-project-files.dita
Add platform profiling controls, triggered by `multi-platform` class. This PR adopts changes from dita-ot/website#408.
Example output:
-   https://preview-pr-300--dita-ot.netlify.app/dev/topics/build-using-dita-command.html
-   https://preview-pr-300--dita-ot.netlify.app/dev/topics/determining-version-of-ditaot.html
-   https://preview-pr-300--dita-ot.netlify.app/dev/topics/using-docker-images.html
=> Add platform profiling

resources/conref-task.dita, topics/using-plugins.ditamap
The "Installing plug-ins" topic did not have any information about or links to being able to use the `configuration.properties` file to install plug-ins. This pull-request adds that information and a reltable link between the installing-plugins and configuration.properties topics.
I have built the website locally using the develop branch of DITA-OT to review the website output.
---
=> Add configuration.properties to Installing plug-ins 

resources/conref-task.dita, topics/determining-version-of-ditaot.dita, topics/dita-command-help.dita, topics/dita2dita.dita, topics/dita2eclipsehelp.dita, topics/dita2html5.dita, topics/dita2htmlhelp.dita, topics/dita2markdown.dita, topics/dita2pdf.dita, topics/dita2xhtml.dita, topics/installing-client.dita, topics/migrating-ant-to-dita.dita, topics/using-dita-command.dita
The command-line samples we provide to illustrate how to do various things with the `dita` command currently use a variety of paths to refer to the `dita` command depending on the assumed current directory.
- `dita-ot-dir/bin/dita …`
- `bin/dita …`
- `dita …`
These changes adjust the installation instructions to explicitly include the addition of the DITA-OT `bin` directory to $PATH, which allows us to simplify the sample commands to all begin with `dita …`.
=> Align command-line examples with `dita` in $PATH

resources/common-toc.ditamap, resources/reltable.ditamap, resources/reusable-components.dita, resources/source-files.ditamap, topics/migration.dita, topics/release-history.dita
Add a topic that includes links to the web pages for the release notes of previous releases. 
When upgrading the recommendation is to read _all_ of the release notes from the base version you're coming from to the target version you're going to, but we don't provide easy access to that history. Some of that information is buried in the migration topic deep in the docs. This page makes that finding those pages easier since people upgrading are likely to be reading the release notes.
Built the "site" target locally. Local HTML and PDF were not specifically tested. 
=> Add links to previous release notes

topics/html-customization-css.dita
As mentioned in [3016](https://github.com/dita-ot/dita-ot/issues/3016), `args.cssroot` requires an absolute path.
See also [2965](https://github.com/dita-ot/dita-ot/issues/2965)
=> Clarify instructions for args.cssroot

.github/workflows/preview.yml
As of October 1, GitHub Actions has [deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) the use of `set-env` and `add-path` commands, so our preview action [fails](https://github.com/dita-ot/docs/runs/1436727242#step:14:3003).
This PR updates the action to use the new [environment files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files) instead.
=> Fix Preview action

samples/docker/Dockerfile, topics/creating-docker-images.dita, topics/using-docker-images.dita
The GitHub Package Registry has been superceded by the GitHub Container Registry. The location of the base Docker Image has therefore changed and needs to be updated in the Docs. GHCR is a public registry and does not require a log-in step
=> Update the docs to point to the container registry

.prettierignore, resources/dita-ot-doc.css
🎨 This PR replaces older custom CSS code in the HTML5 version of the distribution docs with styles based on  [almond.css](https://github.com/alvaromontoro/almond.css):
> Almond.CSS is a collection of class-less CSS styles to make simple websites look better.
This provides a more coherent baseline of modern style constructs that works well in recent browsers and approximates our Bootstrap output on the project website using Almond's built-in theming mechanisms like CSS variables and HSL colors.
The resulting output limits line length to a maximum width of `80ch` for a better reading experience on desktop displays. 🖥️ 
gradlew.bat -PditaHome=C:\path\to\dita-ot html
=> Style HTML output based on Almond.CSS

.github/workflows/prettier.yml
[prettier/plugin-xml](https://github.com/prettier/plugin-xml) dropped support for the `xmlSelfClosingSpace` option in [v1.0.0](https://github.com/prettier/plugin-xml/blob/main/CHANGELOG.md#100---2021-07-14), which causes formatting checks to fail until the extra space is added to self-closing elements.
This pins the plug-in version to the last version that supports the `xmlSelfClosingSpace` option to allow checks to complete successfully in the meantime.
=> Pin Prettier plug-in version in GitHub action

build.gradle
Upgrade the Saxon-HE version in the Gradle build file to the recently released version 10.6.
Ran distribution build from https://github.com/dita-ot/dita-ot/pull/3803, build succeeds. ✅
=> Bump Saxon-HE to version 10.6

reference/preprocess-keyref.dita
@shaneataylor asked in Slack whether key definitions are still written to a file in a temporary directory, believing the information in the documentation to be outdated. @robander confirmed that the docs are incorrect and a temp file is  no longer used.
=> Remove key definition list being written to temp directory

.github/actions/render/action.yml
Install LwDITA 3.3 plug-in for CI build for site deployment.
Add support for `wikidocs` format.
=> Install LwDITA 3.3 plug-in for CI build

.github/workflows/release-debug.yml
The workflow needs to be in the default branch in order to be callable from other repositories. This workflow will be removed once it's tested and the functionality is moved to `release.yml`.
=> Debug GitHub Actions

topics/lwdita-input.dita
Signed-off-by: Darrenn Jackson
Added a section to the LwDITA page to help LwDITA users successful apply conditional processing to their content. This new section explicitly tells users which attribute names to use in the HDITA/MDITA content and in the ditaval content, because these are different.
For those testing/piloting MDITA specifically, when your conditional processing doesn't appear in the output, it's hard to know if it's because this feature isn't yet supported in DITA-OT, or if it's because you set it up wrong.
This is a docs change. Testing is N/A
Docs-only change. This does not introduce any xrefs, conrefs, keyrefs, or other linkages to the rest of the docs.
This doesn't require updates to user plug-ins.
No code testing required.
=> HDITA and MDITA conditional processing guidance

samples/themes/dita-ot-docs-theme.yaml
Draft styling for https://github.com/jelovirt/pdf-generator/pull/90, which adds support for additional domains, including:
- programming domain
- markup domain
- UI domain
- XML domain
Not all of these elements are currently used in the docs, so to keep the theme file readable, we only style those elements that are currently used.
If new elements are added later, styling can be added as necessary.
=> Style additional domain elements in docs theme

resources/theme/.gitrepo, resources/theme/Styles.md
Sync recent changes from https://github.com/jelovirt/pdf-generator/wiki/Styles (`9f2a314` & `4c84af5`), remove duplicate listings & edit descriptions.
These changes have been pushed back to the upstream wiki via [git-subrepo](https://github.com/ingydotnet/git-subrepo), but should not be merged here until a new version of the `com.elovirta.pdf` plug-in is released and bundled with DITA-OT.
> **Note**
>
> DITA-OT 4.0.2 includes `com.elovirta.pdf` version 0.6.0.
> 
> Version 0.6.1 was tagged Nov 12, 2022, but has not yet been published to the plug-in registry or bundled with a toolkit release.
cc/ @jelovirt
=> Update theme reference from plug-in wiki

parameters/plugin-properties-file.dita
Fix incorrect path to `plugin.properties`.
The path was changed in DITA-OT 3.0.
- Bug fix _(non-breaking change which fixes an issue)_
=> Fix path to `plugin.properties`

.github/workflows/prettier.yml
Run Prettier in GitHub Actions via NPM instead of GA action.
Run Prettier check the same way as locally to simplify  configuration.
=> Run Prettier in CI via NPM

.github/workflows/release.yml
Add workflow to update DITA-OT version in GitHub Actions configuration.
Reduce manual work and make it easier to automatically upgrade DITA-OT to latest version.
=> Add workflow to update GitHub Actions configuration

parameters/dita-command-arguments.dita, resources/source-files.ditamap, topics/configuring-proxies.dita, topics/configuring-the-proxy.dita, topics/troubleshooting.ditamap
This PR bundles additional revisions to the HTTP proxy configuration information provided by @EditKoselak in #501, since the [nokia/dita-ot-docs](https://github.com/nokia/dita-ot-docs/) fork is not writeable by DITA-OT docs maintainers.
=> HTTP proxy revisions

topics/using-docker-images.dita
Remove reduncant -it arguments to docker and add --rm to remove the container after use.
Fixes #519
=> Fix Docker usage

topics/creating-docker-images.dita
Change Docker usage to use `--rm` option and remove redundant `-it` per #519.
Followup to #520.
For most users, `--rm` is a better default.
=> Remove image with --rm when running Docker

parameters/dita-command-arguments.dita
Explain the `-no-color` parameter
Parameter deactivates colored logging.
=> Explain the `--no-color` parameter

.github/actions/render/action.yml, .github/workflows/release.yml
Update docs GitHub Actions for 4.2.
=> Update docs GitHub Actions for 4.2

reference/extended-functionality.dita, reference/markdown/Common-syntax.md, reference/processing-structure.dita, resources/dita-ot-doc.css, samples/concepts/tools.xml, samples/taskbook/webtrouble.dita, topics/building-output.dita, topics/implement-saxon-extension-functions.dita, topics/plugin-configfile.dita
All of them were found using `typos`.
=> Fix typos in documentation and code

release-notes/index.dita, resources/key-definitions.ditamap
DITA-OT 4.2.2 release notes.
- Bug fix _(non-breaking change which fixes an issue)_
- Breaking change _(fix or feature that changes existing functionality)_
- What documentation changes are needed for this feature?
_(Provide links to existing documentation topics that will require updates)_
- Will this change affect backwards compatibility or other users' overrides?
=> Draft 4.2.2 Release Notes

.github/workflows/release.yml
Add `author` to PR commits generated by GitHub Actions.
Fix mismatch between `author` and sign-off.
=> Add author to GHA generated PR commits

parameters/ant-parameters-details.dita, parameters/configuration-properties-file.dita, parameters/configuration-properties.dita, parameters/dot-ditaotrc-file.dita, parameters/local-properties-file.dita, parameters/parameters.ditamap, release-notes/index.dita, resources/key-definitions.ditamap, resources/source-files.ditamap, samples/docker/Dockerfile
=> 🚧 Draft 4.2.4 docs

index.dita, parameters/index.dita, parameters/parameters.ditamap, reference/markdown-formats.ditamap, reference/reference.ditamap, resources/common-toc.ditamap, resources/reltable.ditamap, resources/source-files.ditamap, topics/building-output.dita, topics/dita-ot-day-2014.ditamap, topics/dita-ot-day-2015.ditamap, topics/extending.dita, topics/installing.dita, topics/intro.ditamap, topics/output-formats.dita, topics/pdf-customization.dita, topics/plugins-registry.dita, topics/publishing.dita, topics/troubleshooting-overview.dita, topics/using-plugins.ditamap, userguide-book.ditamap
Refactor map hierarchies to simplify top-level navigation for #585.
=> #585: Refactor ToC/parts

topics/plugin-xsltparams.dita
Change Ant parameter from deprecated `if` to `if:set`. This harmonizes `plugin-xsltparams.dita` and `plugin-extension-points-xslt-parameters.dita`.
Replace deprecated `if` attribute with `if:set`.
Local tests
Improvement
All good
=> Change to if:set

topics/pdf-themes.ditamap, topics/sample-pdf-theme.dita
Move the examples from the front to the end of PDF themes.
I found this part confusing. I'd rather have the examples at the end, so that new readers are guided through the features first.
Editorial change
This is a documentation change
=> reorder/rename pdf-themes topics to make them less confusing
